events {
    worker_connections 1024; 
}
http {
    upstream app_cluster {
        server be:3000; 
    }

    server {
        listen 80;  # Listen on port 3000

        location / {
            proxy_pass http://app_cluster;  # Pass requests to the upstream cluster
            proxy_set_header Host $host;  # Preserve original host header
            proxy_set_header X-Real-IP $remote_addr;  # Pass the client's real IP
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;  # Forwarded for IP
            proxy_set_header X-Forwarded-Proto $scheme;  # Forwarded protocol (http or https)
        }
    }
}
